version: "3"

services:
  glovodb:
    image: postgres
    container_name: glovodb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=prisma123
      - POSTGRES_DB=glovodb
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
